### ISSUE TITLE
Instructions unclear

### ISSUE THREAD

**Issue by aScriptingOreo** [henkelmax/upload-curseforge-modpack-action#2]
Hey! I have no idea why, but this is happening
![image](https://user-images.githubusercontent.com/14958916/156193669-40735e3b-e859-4fa2-95b7-54366bfb058f.png)

**Comment by MWG-Logan** [comment]
Little late to the party, but I fixed this on another project of mine by taking a different approach to it.
It looks like they're using releases to prompt the automation, but I initiate mine from accepted pulls to main.

In the code below, I use the manifest instead to obtain the target (new) version number, then extract changelog differences between the previous and new. 

It then creates a release with the changelog as the description, tag as the title, and version number tag from the JSON.

I know it's a bit of a different solution than you asked for, but it is one :)

```
      - name: get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: 'manifest.json'
          prop_path: 'version_number'
      - name: Extract release notes
        id: extract-release-notes
        uses: ffurrer2/extract-release-notes@v1
        with:
          changelog_file: README.md
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{steps.version.outputs.prop}} 
          release_name: ${{steps.version.outputs.prop}} 
          draft: false
          prerelease: false
          body: ${{ steps.extract-release-notes.outputs.release_notes }}
```
